name: release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: suinua/plugin_release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}